# Generated by Django 4.2.4 on 2023-08-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20)),
                ('avatar_url', models.URLField()),
                ('followers', models.CharField(max_length=10)),
                ('following', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('likes', models.CharField(max_length=10)),
                ('share', models.CharField(max_length=10)),
                ('views', models.CharField(max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkapi.profile')),
            ],
        ),
    ]
